#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

# Remove generated mesh (recreated by extrude commands in Allrun)
rm -rf constant/polyMesh

# Remove all log files so Allrun will re-execute every step
rm -f log.*

#------------------------------------------------------------------------------
